DATA_PATH = ""

CELEBA_TRAIN_DATA_PATH = ""
CELEBA_TEST_DATA_PATH = ""

CELEBA_TRAIN_BBOX_ANNOT = ""
CELEBA_TEST_BBOX_ANNOT = ""
CELEBA_TRAIN_LM_ANNOT = ""
CELEBA_TEST_LM_ANNOT = ""

WIDER_TRAIN_DATA_PATH = ""
WIDER_TEST_DATA_PATH = ""